import cron from 'node-cron';
import { attendanceDB } from '../config/database.js';
import { buildReport } from '../services/darServices/DARReportAPI.js';
import { sendEmail } from '../services/auth/emailService.js';

// ─────────────────────────────────────────────────────────────────────────────
// DATE RANGE HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function isoDate(d) {
    return d.toISOString().split('T')[0];
}

function prevDayRange() {
    const d = new Date();
    d.setDate(d.getDate() - 1);
    const ds = isoDate(d);
    return { start: ds, end: ds };
}

function prevWeekRange() {
    // Last completed Mon → Sun
    const today = new Date();
    const dayOfWeek = today.getDay(); // 0 = Sun
    const daysToLastSunday = dayOfWeek === 0 ? 7 : dayOfWeek;
    const sunday = new Date(today);
    sunday.setDate(today.getDate() - daysToLastSunday);
    const monday = new Date(sunday);
    monday.setDate(sunday.getDate() - 6);
    return { start: isoDate(monday), end: isoDate(sunday) };
}

function prevMonthRange() {
    const today = new Date();
    const lastDayPrev = new Date(today.getFullYear(), today.getMonth(), 0);
    const firstDayPrev = new Date(lastDayPrev.getFullYear(), lastDayPrev.getMonth(), 1);
    return { start: isoDate(firstDayPrev), end: isoDate(lastDayPrev) };
}

// ─────────────────────────────────────────────────────────────────────────────
// REPORT RUNNER
// ─────────────────────────────────────────────────────────────────────────────

async function runDARReport(type, dateRange) {
    const { start, end } = dateRange;
    console.log(`📊 [DARReportScheduler] Running ${type} report  ${start} → ${end}`);

    try {
        // Fetch active schedules for this frequency
        const schedules = await attendanceDB('dar_report_schedules')
            .where({ frequency: type, is_active: true });

        if (schedules.length === 0) {
            console.log(`📊 No active ${type} schedules, skipping.`);
            return;
        }

        for (const schedule of schedules) {
            const { schedule_id, org_id, email_to } = schedule;
            try {
                const reportData = await buildReport(org_id, [], start, end, type);
                if (reportData.length === 0) {
                    console.log(`  ⚠  Org ${org_id} — no employees, skipped`);
                    continue;
                }

                console.log(`  ✅ Org ${org_id} — ${reportData.length} employees`);

                // Send a short narrative summary email if recipient configured
                if (email_to) {
                    const periodLabel = type.charAt(0).toUpperCase() + type.slice(1);
                    const rangeLabel = start === end ? start : `${start} to ${end}`;
                    const employeeBlocks = reportData.slice(0, 12).map((employee) => `
                        <div style="margin-bottom:14px; padding-bottom:14px; border-bottom:1px solid #e5e7eb;">
                            <p style="margin:0 0 6px; font-weight:600; color:#111827;">${employee.user_name}</p>
                            <p style="margin:0 0 6px; color:#374151;">${employee.report_summary}</p>
                            <p style="margin:0; color:#4b5563; white-space:pre-line;">${employee.work_summary}</p>
                        </div>
                    `).join('');
                    const remainingCount = Math.max(0, reportData.length - 12);

                    const recipients = email_to.split(',').map((e) => e.trim()).filter(Boolean);
                    for (const to of recipients) {
                        const result = await sendEmail({
                            to,
                            subject: `DAR ${periodLabel} Report — ${rangeLabel}`,
                            text: `DAR ${periodLabel} summary for ${rangeLabel}. Employees covered: ${reportData.length}.`,
                            html: `<p>Please find the <strong>DAR ${periodLabel} summary</strong> for the period <strong>${rangeLabel}</strong>.</p>
                     <p style="margin:0 0 10px; color:#4b5563;">Employees covered: ${reportData.length}</p>
                     ${employeeBlocks}
                     ${remainingCount > 0 ? `<p style="color:#6b7280;">${remainingCount} more employee summaries were omitted from the email preview.</p>` : ''}
                     <p style="color:#6b7280;font-size:12px;">Auto-generated by MANO Attendance System.</p>`,
                        });
                        if (result.ok) {
                            console.log(`     📧 Emailed to ${to}`);
                        } else {
                            console.error(`     ❌ Email to ${to} failed:`, result.error);
                        }
                    }
                }

                // Log to history
                await attendanceDB('dar_report_history').insert({
                    org_id,
                    user_id: null,
                    period_type: type,
                    date_from: start,
                    date_to: end,
                    trigger_type: 'scheduled',
                    status: 'done',
                    generated_by: 'cron',
                });

                // Update last_run_at
                await attendanceDB('dar_report_schedules')
                    .where('schedule_id', schedule_id)
                    .update({ last_run_at: attendanceDB.fn.now() });

            } catch (orgErr) {
                console.error(`  ❌ Org ${org_id} ${type} report failed:`, orgErr.message);
                attendanceDB('dar_report_history').insert({
                    org_id, user_id: null, period_type: type,
                    date_from: start, date_to: end,
                    trigger_type: 'scheduled', status: 'failed', generated_by: 'cron',
                }).catch(() => { });
            }
        }

        console.log(`📊 [DARReportScheduler] ${type} report complete.`);
    } catch (err) {
        console.error(`❌ [DARReportScheduler] ${type} report crashed:`, err.message);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// INIT — called from server.js inside server.listen()
// ─────────────────────────────────────────────────────────────────────────────

export function initDARReportScheduler() {
    // Daily: 11:30 PM every day — covers that day's data
    cron.schedule('30 23 * * *', () => {
        runDARReport('daily', prevDayRange());
    });

    // Weekly: Monday 7:00 AM — covers previous Mon → Sun
    cron.schedule('0 7 * * 1', () => {
        runDARReport('weekly', prevWeekRange());
    });

    // Monthly: 1st of month 6:00 AM — covers previous full month
    cron.schedule('0 6 1 * *', () => {
        runDARReport('monthly', prevMonthRange());
    });

    console.log('📊 DAR Report Scheduler initialised  (daily@23:30 | weekly@Mon 07:00 | monthly@1st 06:00)');
}
